# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautifulOldAge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeautifulOldAge

  target 'BeautifulOldAgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeautifulOldAgeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'WechatOpenSDK'
pod 'AliPay'
pod 'JPush'




end
